import {readFile,writeFile,readdir} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=new URL('../../',import.meta.url), workspace=new URL('../',root);
const baseline=JSON.parse(await readFile(new URL('tools/mvu/contracts/api-surface-baseline.json',root),'utf8'));
const manifest=JSON.parse(await readFile(new URL('app/src/main/assets/compat/manifest.json',root),'utf8'));
const sources=[];
for(const [directory,key] of [['js-slash-runner','tavern_helper'],['ST-Prompt-Template','prompt_template']]) {
  const repository=new URL(directory+'/',workspace);
  const revision=execFileSync('git',['-C',fileURLToPath(repository),'rev-parse','HEAD'],{encoding:'utf8'}).trim();
  if(revision!==manifest.upstream[key])throw Error(`Reference revision changed: ${directory}`);
  async function scan(folder) {
    for(const file of await readdir(folder,{withFileTypes:true})) {
      const url=new URL(file.name+(file.isDirectory()?'/':''),folder);
      if(file.isDirectory())await scan(url);
      else if(/\.(?:ts|js)$/.test(file.name))sources.push({repository:directory,revision,path:fileURLToPath(url).slice(fileURLToPath(repository).length).replaceAll('\\','/'),text:await readFile(url,'utf8')});
    }
  }
  await scan(new URL('src/',repository));
}
const contracts=baseline.entries.map(entry=>{
  const name=entry.path.split('.').at(-1),names=[name,'_'+name];
  const definitions=[];
  for(const source of sources) for(const candidate of names) {
    const escaped=candidate.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
    const re=new RegExp(`(?:export\\s+)?(?:async\\s+)?function\\s+${escaped}(?:\\s*<[^;{]*?>)?\\s*\\(|(?:export\\s+)?(?:const|let)\\s+${escaped}\\s*(?::[^=;]+)?=`,'g');
    for(const match of source.text.matchAll(re))definitions.push({repository:source.repository,revision:source.revision,path:source.path,line:source.text.slice(0,match.index).split('\n').length});
  }
  return {...entry,sourceCandidates:definitions,signatureStatus:'pending',exceptionContractStatus:'pending',
    evidence:/\.(getVariables|replaceVariables|getChatMessages|setChatMessages|evalTemplate|evaltemplate|updateVariablesWith|insertVariables|insertOrAssignVariables|deleteVariable)$/.test(entry.path)?'Partial coverage only; see protocol baseline and message mutation golden tests':null};
});
await writeFile(new URL('tools/mvu/contracts/api-contracts.json',root),JSON.stringify({formatVersion:1,contracts},null,2)+'\n');
const lines=['# Public API contract audit','','Generated by `tools/mvu/api-matrix.mjs` from the frozen surface. Aliases count separately.',
  'Source candidates are navigation aids; overloads, `_bind` behavior, errors and lifecycle still require contract review. Arity is JavaScript `function.length`, not a complete signature.',
  'A placeholder candidate is a static heuristic, not proof that the entire method is missing. No row is accepted merely because it is nonempty. All full contracts remain pending.',
  '', '| API | Arity | Placeholder candidate | Source candidates | Contract |', '| --- | ---: | --- | --- | --- |'];
for(const entry of contracts) {
  const source=entry.sourceCandidates.slice(0,3).map(s=>`${s.repository}/${s.path}:${s.line}`).join('<br>')||'Unresolved';
  lines.push(`| \`${entry.path}\` | ${entry.arity} | ${entry.placeholderCandidate?'Yes':'No'} | ${source} | Pending |`);
}
await writeFile(new URL('docs/MVU-API-MATRIX.md',root),lines.join('\n')+'\n');
console.log(JSON.stringify({entries:contracts.length,placeholderCandidates:contracts.filter(e=>e.placeholderCandidate).length,withSourceCandidates:contracts.filter(e=>e.sourceCandidates.length).length,accepted:0}));
