import {readFile,writeFile,readdir} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=new URL('../../',import.meta.url), workspace=new URL('../',root);
const baseline=JSON.parse(await readFile(new URL('tools/mvu/contracts/api-surface-baseline.json',root),'utf8'));
const manifest=JSON.parse(await readFile(new URL('app/src/main/assets/compat/manifest.json',root),'utf8'));
const sources=[];
for(const [directory,key] of [['js-slash-runner','tavern_helper'],['ST-Prompt-Template','prompt_template']]) {
  const repository=new URL(directory+'/',workspace);
  const revision=execFileSync('git',['-C',fileURLToPath(repository),'rev-parse','HEAD'],{encoding:'utf8'}).trim();
  if(revision!==manifest.upstream[key])throw Error(`Reference revision changed: ${directory}`);
  async function scan(folder) {
    for(const file of await readdir(folder,{withFileTypes:true})) {
      const url=new URL(file.name+(file.isDirectory()?'/':''),folder);
      if(file.isDirectory())await scan(url);
      else if(/\.(?:ts|js)$/.test(file.name))sources.push({repository:directory,revision,path:fileURLToPath(url).slice(fileURLToPath(repository).length).replaceAll('\\','/'),text:await readFile(url,'utf8')});
    }
  }
  await scan(new URL('src/',repository));
}
const contracts=baseline.entries.map(entry=>{
  const name=entry.path.split('.').at(-1),names=[name,'_'+name];
  const definitions=[];
  for(const source of sources) for(const candidate of names) {
    const escaped=candidate.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
    const re=new RegExp(`(?:export\\s+)?(?:async\\s+)?function\\s+${escaped}(?:\\s*<[^;{]*?>)?\\s*\\(|(?:export\\s+)?(?:const|let)\\s+${escaped}\\s*(?::[^=;]+)?=`,'g');
    for(const match of source.text.matchAll(re))definitions.push({repository:source.repository,revision:source.revision,path:source.path,line:source.text.slice(0,match.index).split('\n').length});
  }
  return {...entry,sourceCandidates:definitions,signatureStatus:'pending',exceptionContractStatus:'pending',
    evidence:/\.(getVariables|replaceVariables|getChatMessages|setChatMessages|evalTemplate|evaltemplate|updateVariablesWith|insertVariables|insertOrAssignVariables|deleteVariable)$/.test(entry.path)?'Partial coverage only; see protocol baseline and message mutation golden tests':null};
});
await writeFile(new URL('tools/mvu/contracts/api-contracts.json',root),JSON.stringify({formatVersion:1,contracts},null,2)+'\n');
const lines=['# Public API contract audit','','Generated by `tools/mvu/api-matrix.mjs` from the frozen surface. Aliases count separately.',
  'Source candidates are navigation aids; overloads, `_bind` behavior, errors and lifecycle still require contract review. Arity is JavaScript `function.length`, not a complete signature.',
  'A placeholder candidate is a static heuristic, not proof that the entire method is missing. No row is accepted merely because it is nonempty. All full contracts remain pending.',
  '', '| API | Arity | Placeholder candidate | Source candidates | Contract |', '| --- | ---: | --- | --- | --- |'];
for(const entry of contracts) {
  const source=entry.sourceCandidates.slice(0,3).map(s=>`${s.repository}/${s.path}:${s.line}`).join('<br>')||'Unresolved';
  lines.push(`| \`${entry.path}\` | ${entry.arity} | ${entry.placeholderCandidate?'Yes':'No'} | ${source} | Pending |`);
}
// Hand-maintained section: the EJS template *evaluation context* surface.
// These functions/constants live inside template rendering (template.js env
// on WebView, PromptTemplateExpressionEvaluator on the Kotlin fallback), not
// on any host global, so the audit above cannot enumerate them. The
// 2026-09-25 audit missed this namespace entirely and let it drift until the
// 玄泽纪 card crashed on `injectPrompt is not defined`; keep it listed here.
// Status vocabulary: implemented (both paths) / JS-only / stub / missing.
lines.push('', '## EJS template bare functions (ST-Prompt-Template prepareContext surface)', '',
  'Names available inside `<% %>` templates per ST-Prompt-Template `ejs.ts` prepareContext + SHARE_CONTEXT. Same-name script-extension APIs (`TavernHelper.injectPrompts` plural, `window.getChatMessages`) are different namespaces — do not conflate.',
  '', '| Name | Status | Notes |', '| --- | --- | --- |');
const templateSurface = [
  ['getvar', 'implemented', 'reads merged cache (global<local<message); options: scope shorthand/flags/merge/results/defaults'],
  ['setvar', 'implemented', 'ST default scope = message (variables.ts:307)'],
  ['getLocalVar / getGlobalVar / getMessageVar', 'implemented', ''],
  ['setLocalVar / setGlobalVar / setMessageVar', 'implemented', ''],
  ['incvar / decvar', 'implemented', 'read cache, write message by default'],
  ['incLocalVar / incGlobalVar / incMessageVar', 'implemented', ''],
  ['decLocalVar / decGlobalVar / decMessageVar', 'implemented', ''],
  ['delvar / delLocalVar / delGlobalVar / delMessageVar', 'implemented', 'delvar defaults to message scope'],
  ['insvar / insertLocalVar / insertGlobalVar / insertMessageVar', 'implemented', 'array push / index splice'],
  ['define', 'implemented', ''],
  ['getwi / getWorldInfo', 'implemented', 'no RegExp entry matching, no data-bound activation context (ST diverges)'],
  ['injectPrompt / getPromptsInjected / hasPromptsInjected', 'implemented', 'module-level registry in template.js; sticky decayed once per build; forceOutlet generate-phase semantics (handler.ts:247/376)'],
  ['parseJSON', 'implemented', 'repair subset of jsonrepair: trailing commas, unquoted keys, single quotes'],
  ['jsonPatch', 'implemented', 'RFC 6902 incl. "-" append; test failure returns original doc'],
  ['patchVariables', 'implemented', 'read-patch-write; default message scope'],
  ['getChatMessage / getChatMessages / matchChatMessages', 'implemented', 'chat floors passed by PromptEngine; content macro-expanded; regex re-application not replicated'],
  ['getVar / setVar / getAllVariables', 'implemented', 'Tellev extras (ST aliases/none)'],
  ['include', 'divergent', 'Tellev renders a worldbook entry by name; ST include is an unimplemented stub returning empty'],
  ['SillyTavern', 'stub', 'empty context; getContext() returns {}'],
  ['execute', 'stub', 'async () => \'\'; no STscript engine'],
  ['faker', 'stub', 'declared undefined; lib not bundled'],
  ['print', 'implemented', 'EJS outputFunctionName built-in'],
  ['activewi / activateWorldInfo / activateWorldInfoByKeywords / selectActivatedEntries', 'implemented', 'local activation registry readable via getActivatedWIEntries; mid-build re-scan unsupported so applyActivateWorldInfo warns once; registry cleared per build by the deactivate hook'],
  ['activateRegex', 'missing', 'regex activation has no template-path pipeline'],
  ['getWorldInfoData / getWorldInfoActivatedData / getEnabledWorldInfoEntries / getEnabledLoreBooks', 'implemented', 'worldCatalog now carries raw entry fields; entries shaped to ST WorldInfoEntry (numeric uid, @@decorators stripped, world binding); enabled books = distinct catalog books; order-stable sort, not ST position sort; catalog content is macro/regex pre-expanded'],
  ['getCharData / getCharaData / getchar / getchr / getChara', 'implemented', 'render request carries request.character (single-card roster); getchr family renders DEFAULT_CHAR_DEFINE with char/user substitution; other characters resolve null'],
  ['getpreset / getprp / getPresetPrompt', 'stub', 'no preset source in template rendering; one-time warn, returns empty'],
  ['getqr / getQuickReply / getQuickReplyData', 'stub', 'no quick-reply source; one-time warn, empty/null'],
  ['evalTemplate', 'implemented', 'nested EJS evaluation; data merged into the live env; char/user re-substituted'],
  ['applyVarYamlAnnotate', 'implemented', 'YAML dump without schema; with schema fills values into the document tree (upstream setIn uses the outer key, treated as an upstream bug)'],
  ['setVariableSchema / findVariables', 'stub', 'schema stored nowhere (returns undefined); historical floors carry no per-floor variables so findVariables returns {}'],
  ['getWorldInfoEntries / getWorldInfoEntry / getWorldInfoEntryContent / getWorldInfoComments', 'implemented', 'documented reference names beyond the ejs.ts mounts; safe superset'],
  ['getCharacterDefine', 'implemented', 'v1 field normalization incl. mes_example <START> fencing'],
  ['getActivatedWIEntries / deactivateActivateWorldInfo / applyActivateWorldInfo', 'implemented', 'registry readers; applyActivateWorldInfo warns once (no mid-build re-scan)'],
  ['getUserAvatarURL / getCharacterAvaterURL', 'stub', 'no avatar URLs in the render path'],
  ['userName / charName / assistantName / name1 / name2 / user / char', 'implemented', 'constants'],
  ['lastMessage / lastUserMessage / lastCharMessage', 'implemented', 'constants'],
  ['lastMessageId / lastUserMessageId / lastCharMessageId', 'implemented', 'numbers; visible-message index base (ST uses full chat)'],
  ['characterId / chatId / model / runType / generateType', 'implemented', 'chatId empty; runType always "generate"; generateType always "normal" (no swipe/continue distinction)'],
  ['charLoreBook / userLoreBook / chatLoreBook', 'implemented', 'charLoreBook binds only when the card ships an embedded book; others null'],
  ['groups / groupId', 'implemented', 'empty stubs'],
  ['charAvatar / userAvatar', 'implemented', 'empty-string stubs'],
  ['variables', 'implemented', 'live cache object (setvar-synced); message/local/global layers merged'],
  ['LAST_SEND_TOKENS / LAST_SEND_CHARS / LAST_RECEIVE_TOKENS / LAST_RECEIVE_CHARS', 'missing', 'written post-generation in ST'],
  ['message_id / is_last / is_user / is_system / name (render phase)', 'implemented', 'chat floors carry a messageContext payload (PromptTemplateMessageContext); system prompt renders with them unset'],
  ['swipe_id (render phase)', 'missing', 'Tellev carries no per-floor swipe index'],
  ['prompt_template_prepare event', 'missing', 'script hook into context preparation'],
];
for(const [name,status,notes] of templateSurface) {
  lines.push(`| \`${name}\` | ${status} | ${notes || '—'} |`);
}
// TavernHelper script surface (extension WebView: inline shim + host.js overrides).
lines.push('', '## TavernHelper script surface (extension WebView)', '',
  'Families on `TavernHelper`/`window` as consumed by card scripts. Real = persists through the virtual API and is visible to the next generation (the runtime re-reads world books per build).', '',
  '| Family | Status | Notes |', '| --- | --- | --- |');
const scriptSurface = [
  ['variables (get/replace/insert/update/delete/getAll, message scope)', 'real', 'host.js overrides; message scope through per-floor native bridge'],
  ['events (eventOn/Once/MakeFirst/MakeLast/Emit/...) + tavern_events/iframe_events', 'real', 'eventSource bridge; per-frame registration DOM'],
  ['getChatMessages / setChatMessages / setChatMessage', 'real', 'stSetChatMessages round trip incl. MVU variable-write commit wait'],
  ['createChatMessages', 'real', 'POST /api/chats/{id}/messages/insert; insert_before semantics incl. negative index'],
  ['deleteChatMessages', 'real', 'POST /api/chats/{id}/messages/delete by normalized floor ids'],
  ['rotateChatMessages', 'stub', 'swipe rotation needs generation; honest no-op'],
  ['worldbook reads (getLorebookEntries/getWorldbook/getWorldbookNames/...)','real','ST lorebook entry shape + v4 WorldbookEntry shape (strategy/position objects)'],
  ['worldbook writes (create/delete/replace/updateWorldbookWith, lorebook entry family)', 'real', 'read-modify-write of the full book via POST /api/worlds; effective next generation'],
  ['deleteWorldbook', 'real', 'DELETE /api/worlds/{id}'],
  ['rebindGlobalWorldbooks', 'real', 'POST /api/worldinfo/disabled activation-set write-back'],
  ['rebindCharWorldbooks / rebindChatWorldbook / getOrCreateChatWorldbook', 'stub', 'Tellev has no per-character additional books nor chat-bound books'],
  ['getCharLorebooks / getCharWorldbookNames / getGlobalWorldbookNames / getLorebookSettings', 'real', 'from the live context snapshot'],
  ['presets (get/load/set/create/replace/update/rename/deletePreset, getLoadedPresetName)', 'real', '/api/presets routes'],
  ['triggerSlash / triggerSlashWithResult / addSlashCommand', 'real', 'native slash engine; triggerSlash rejects on isError and returns the pipe'],
  ['regex (getTavernRegexes/replaceTavernRegexes/updateTavernRegexesWith)', 'real', 'upstream option-object order; legacy positional (charId, regexes) still accepted'],
  ['formatAsDisplayedMessage', 'real', 'macro substitution; card regex applied upstream'],
  ['formatAsTavernRegexedString', 'stub', 'ScopedScript reshaping not implemented'],
  ['injectPrompts / uninjectPrompts', 'real', 'position/depth/role/shouldScan via stInjectPromptWithOptions; once via GENERATION_ENDED'],
  ['generate / generateRaw / getModelList', 'real', '/api/backends/chat-completions routes'],
  ['characters / personas (get/list/create/replace/updateWith/delete)', 'real', '/api/characters, /api/personas routes; upstream CharacterData reshaping not replicated'],
  ['audio family (play/pause/lists/settings/audioEnable/...)', 'stub', 'no audio pipeline in the extension WebView'],
  ['initializeGlobal / waitGlobalInitialized', 'real', 'waiter registry with polling backstop'],
  ['substitudeMacros / getLastMessageId / getMessageId / errorCatched', 'real', '—'],
  ['registerVariableSchema', 'partial', 'schema stored but not validated on write'],
];
for(const [family,status,notes] of scriptSurface) {
  lines.push(`| \`${family}\` | ${status} | ${notes} |`);
}
lines.push('', 'Coverage 2026-09-26: 53 of 62 function names implemented on the production WebView path (was 38); the remaining 9 are stubs or missing: activateRegex, getpreset/getprp/getPresetPrompt, getqr/getQuickReply/getQuickReplyData, setVariableSchema, findVariables, plus the four LAST_* counters and swipe_id/prompt_template_prepare.');
await writeFile(new URL('docs/MVU-API-MATRIX.md',root),lines.join('\n')+'\n');
console.log(JSON.stringify({entries:contracts.length,placeholderCandidates:contracts.filter(e=>e.placeholderCandidate).length,withSourceCandidates:contracts.filter(e=>e.sourceCandidates.length).length,accepted:0}));
