import {readFile,writeFile,readdir} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=new URL('../../',import.meta.url), workspace=new URL('../',root);
const baseline=JSON.parse(await readFile(new URL('tools/mvu/contracts/api-surface-baseline.json',root),'utf8'));
const manifest=JSON.parse(await readFile(new URL('app/src/main/assets/compat/manifest.json',root),'utf8'));
const sources=[];
for(const [directory,key] of [['js-slash-runner','tavern_helper'],['ST-Prompt-Template','prompt_template']]) {
  const repository=new URL(directory+'/',workspace);
  const revision=execFileSync('git',['-C',fileURLToPath(repository),'rev-parse','HEAD'],{encoding:'utf8'}).trim();
  if(revision!==manifest.upstream[key])throw Error(`Reference revision changed: ${directory}`);
  async function scan(folder) {
    for(const file of await readdir(folder,{withFileTypes:true})) {
      const url=new URL(file.name+(file.isDirectory()?'/':''),folder);
      if(file.isDirectory())await scan(url);
      else if(/\.(?:ts|js)$/.test(file.name))sources.push({repository:directory,revision,path:fileURLToPath(url).slice(fileURLToPath(repository).length).replaceAll('\\','/'),text:await readFile(url,'utf8')});
    }
  }
  await scan(new URL('src/',repository));
}
const contracts=baseline.entries.map(entry=>{
  const name=entry.path.split('.').at(-1),names=[name,'_'+name];
  const definitions=[];
  for(const source of sources) for(const candidate of names) {
    const escaped=candidate.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
    const re=new RegExp(`(?:export\\s+)?(?:async\\s+)?function\\s+${escaped}(?:\\s*<[^;{]*?>)?\\s*\\(|(?:export\\s+)?(?:const|let)\\s+${escaped}\\s*(?::[^=;]+)?=`,'g');
    for(const match of source.text.matchAll(re))definitions.push({repository:source.repository,revision:source.revision,path:source.path,line:source.text.slice(0,match.index).split('\n').length});
  }
  return {...entry,sourceCandidates:definitions,signatureStatus:'pending',exceptionContractStatus:'pending',
    evidence:/\.(getVariables|replaceVariables|getChatMessages|setChatMessages|evalTemplate|evaltemplate|updateVariablesWith|insertVariables|insertOrAssignVariables|deleteVariable)$/.test(entry.path)?'Partial coverage only; see protocol baseline and message mutation golden tests':null};
});
await writeFile(new URL('tools/mvu/contracts/api-contracts.json',root),JSON.stringify({formatVersion:1,contracts},null,2)+'\n');
const lines=['# Public API contract audit','','Generated by `tools/mvu/api-matrix.mjs` from the frozen surface. Aliases count separately.',
  'Source candidates are navigation aids; overloads, `_bind` behavior, errors and lifecycle still require contract review. Arity is JavaScript `function.length`, not a complete signature.',
  'A placeholder candidate is a static heuristic, not proof that the entire method is missing. No row is accepted merely because it is nonempty. All full contracts remain pending.',
  '', '| API | Arity | Placeholder candidate | Source candidates | Contract |', '| --- | ---: | --- | --- | --- |'];
for(const entry of contracts) {
  const source=entry.sourceCandidates.slice(0,3).map(s=>`${s.repository}/${s.path}:${s.line}`).join('<br>')||'Unresolved';
  lines.push(`| \`${entry.path}\` | ${entry.arity} | ${entry.placeholderCandidate?'Yes':'No'} | ${source} | Pending |`);
}
// Hand-maintained section: the EJS template *evaluation context* surface.
// These functions/constants live inside template rendering (template.js env
// on WebView, PromptTemplateExpressionEvaluator on the Kotlin fallback), not
// on any host global, so the audit above cannot enumerate them. The
// 2026-09-25 audit missed this namespace entirely and let it drift until the
// 玄泽纪 card crashed on `injectPrompt is not defined`; keep it listed here.
// Status vocabulary: implemented (both paths) / JS-only / stub / missing.
lines.push('', '## EJS template bare functions (ST-Prompt-Template prepareContext surface)', '',
  'Names available inside `<% %>` templates per ST-Prompt-Template `ejs.ts` prepareContext + SHARE_CONTEXT. Same-name script-extension APIs (`TavernHelper.injectPrompts` plural, `window.getChatMessages`) are different namespaces — do not conflate.',
  '', '| Name | Status | Notes |', '| --- | --- | --- |');
const templateSurface = [
  ['getvar', 'implemented', 'reads merged cache (global<local<message); options: scope shorthand/flags/merge/results/defaults'],
  ['setvar', 'implemented', 'ST default scope = message (variables.ts:307)'],
  ['getLocalVar / getGlobalVar / getMessageVar', 'implemented', ''],
  ['setLocalVar / setGlobalVar / setMessageVar', 'implemented', ''],
  ['incvar / decvar', 'implemented', 'read cache, write message by default'],
  ['incLocalVar / incGlobalVar / incMessageVar', 'implemented', ''],
  ['decLocalVar / decGlobalVar / decMessageVar', 'implemented', ''],
  ['delvar / delLocalVar / delGlobalVar / delMessageVar', 'implemented', 'delvar defaults to message scope'],
  ['insvar / insertLocalVar / insertGlobalVar / insertMessageVar', 'implemented', 'array push / index splice'],
  ['define', 'implemented', ''],
  ['getwi / getWorldInfo', 'implemented', 'no RegExp entry matching, no data-bound activation context (ST diverges)'],
  ['injectPrompt / getPromptsInjected / hasPromptsInjected', 'implemented', 'module-level registry in template.js; sticky decayed once per build; forceOutlet generate-phase semantics (handler.ts:247/376)'],
  ['parseJSON', 'implemented', 'repair subset of jsonrepair: trailing commas, unquoted keys, single quotes'],
  ['jsonPatch', 'implemented', 'RFC 6902 incl. "-" append; test failure returns original doc'],
  ['patchVariables', 'implemented', 'read-patch-write; default message scope'],
  ['getChatMessage / getChatMessages / matchChatMessages', 'implemented', 'chat floors passed by PromptEngine; content macro-expanded; regex re-application not replicated'],
  ['getVar / setVar / getAllVariables', 'implemented', 'Tellev extras (ST aliases/none)'],
  ['include', 'divergent', 'Tellev renders a worldbook entry by name; ST include is an unimplemented stub returning empty'],
  ['SillyTavern', 'stub', 'empty context; getContext() returns {}'],
  ['execute', 'stub', 'async () => \'\'; no STscript engine'],
  ['faker', 'stub', 'declared undefined; lib not bundled'],
  ['print', 'implemented', 'EJS outputFunctionName built-in'],
  ['activateRegex / activateWorldInfo / activewi / activateWorldInfoByKeywords / selectActivatedEntries', 'missing', 'worldbook activation family'],
  ['getWorldInfoData / getWorldInfoActivatedData / getEnabledWorldInfoEntries / getEnabledLoreBooks', 'missing', 'worldbook data family'],
  ['getCharData / getCharaData / getchar / getchr / getChara', 'missing', 'character data family'],
  ['getpreset / getprp / getPresetPrompt', 'missing', 'preset prompt family'],
  ['getqr / getQuickReply / getQuickReplyData', 'missing', 'quick reply family'],
  ['evalTemplate', 'missing', 'nested template evaluation (EjsTemplate.evalTemplate exists script-side)'],
  ['setVariableSchema / findVariables / applyVarYamlAnnotate', 'missing', 'variable schema/annotation family'],
  ['userName / charName / assistantName / name1 / name2 / user / char', 'implemented', 'constants'],
  ['lastMessage / lastUserMessage / lastCharMessage', 'implemented', 'constants'],
  ['lastMessageId / lastUserMessageId / lastCharMessageId', 'implemented', 'numbers; visible-message index base (ST uses full chat)'],
  ['characterId / chatId / model / runType / generateType', 'implemented', 'chatId empty; runType always "generate"; generateType always "normal" (no swipe/continue distinction)'],
  ['charLoreBook / userLoreBook / chatLoreBook', 'implemented', 'charLoreBook binds only when the card ships an embedded book; others null'],
  ['groups / groupId', 'implemented', 'empty stubs'],
  ['charAvatar / userAvatar', 'implemented', 'empty-string stubs'],
  ['variables', 'implemented', 'live cache object (setvar-synced); message/local/global layers merged'],
  ['LAST_SEND_TOKENS / LAST_SEND_CHARS / LAST_RECEIVE_TOKENS / LAST_RECEIVE_CHARS', 'missing', 'written post-generation in ST'],
  ['message_id / swipe_id / is_last / is_user / is_system / name (render phase)', 'missing', 'ST render-phase per-floor fields'],
  ['prompt_template_prepare event', 'missing', 'script hook into context preparation'],
];
for(const [name,status,notes] of templateSurface) {
  lines.push(`| \`${name}\` | ${status} | ${notes || '—'} |`);
}
lines.push('', 'Coverage 2026-09-25: 38 of 62 function names implemented on the production WebView path (was 12); constants declared except the four LAST_* counters and render-phase fields.');
await writeFile(new URL('docs/MVU-API-MATRIX.md',root),lines.join('\n')+'\n');
console.log(JSON.stringify({entries:contracts.length,placeholderCandidates:contracts.filter(e=>e.placeholderCandidate).length,withSourceCandidates:contracts.filter(e=>e.sourceCandidates.length).length,accepted:0}));
