package app.tellev.core.storage

import java.nio.file.Path

data class StDirectoryLayout(
    val root: Path,
    val thumbnails: Path,
    val thumbnailsBg: Path,
    val thumbnailsAvatar: Path,
    val thumbnailsPersona: Path,
    val worlds: Path,
    val user: Path,
    val avatars: Path,
    val userImages: Path,
    val groups: Path,
    val groupChats: Path,
    val chats: Path,
    val characters: Path,
    val backgrounds: Path,
    val novelAiSettings: Path,
    val koboldAiSettings: Path,
    val openAiSettings: Path,
    val textGenSettings: Path,
    val themes: Path,
    val movingUi: Path,
    val extensions: Path,
    val instruct: Path,
    val context: Path,
    val quickReplies: Path,
    val assets: Path,
    val comfyWorkflows: Path,
    val files: Path,
    val vectors: Path,
    val backups: Path,
    val systemPrompts: Path,
    val reasoning: Path,
    // tellev-owned app state (not a SillyTavern file format). Single file, not
    // a directory, so it is intentionally absent from allDirectories.
    val worldInfoActivation: Path,
) {
    val allDirectories: List<Path> = listOf(
        root,
        thumbnails,
        thumbnailsBg,
        thumbnailsAvatar,
        thumbnailsPersona,
        worlds,
        user,
        avatars,
        userImages,
        groups,
        groupChats,
        chats,
        characters,
        backgrounds,
        novelAiSettings,
        koboldAiSettings,
        openAiSettings,
        textGenSettings,
        themes,
        movingUi,
        extensions,
        instruct,
        context,
        quickReplies,
        assets,
        comfyWorkflows,
        files,
        vectors,
        backups,
        systemPrompts,
        reasoning,
    )

    companion object {
        fun fromRoot(root: Path): StDirectoryLayout = StDirectoryLayout(
            root = root,
            thumbnails = root.resolve("thumbnails"),
            thumbnailsBg = root.resolve("thumbnails/bg"),
            thumbnailsAvatar = root.resolve("thumbnails/avatar"),
            thumbnailsPersona = root.resolve("thumbnails/persona"),
            worlds = root.resolve("worlds"),
            user = root.resolve("user"),
            avatars = root.resolve("User Avatars"),
            userImages = root.resolve("user/images"),
            groups = root.resolve("groups"),
            groupChats = root.resolve("group chats"),
            chats = root.resolve("chats"),
            characters = root.resolve("characters"),
            backgrounds = root.resolve("backgrounds"),
            novelAiSettings = root.resolve("NovelAI Settings"),
            koboldAiSettings = root.resolve("KoboldAI Settings"),
            openAiSettings = root.resolve("OpenAI Settings"),
            textGenSettings = root.resolve("TextGen Settings"),
            themes = root.resolve("themes"),
            movingUi = root.resolve("movingUI"),
            extensions = root.resolve("extensions"),
            instruct = root.resolve("instruct"),
            context = root.resolve("context"),
            quickReplies = root.resolve("QuickReplies"),
            assets = root.resolve("assets"),
            comfyWorkflows = root.resolve("user/workflows"),
            files = root.resolve("user/files"),
            vectors = root.resolve("vectors"),
            backups = root.resolve("backups"),
            systemPrompts = root.resolve("sysprompt"),
            reasoning = root.resolve("reasoning"),
            worldInfoActivation = root.resolve("world-info-activation.json"),
        )
    }
}

