package app.tellev.core.i18n

import app.tellev.R

// GENERATED by tools/i18n_consolidate.py — do not edit by hand.
// Sources: _i18n/*.tsv (zh) + _i18n/translations.tsv (en/ja/ko).
object S {
    const val chars_export_write_failed = "chars_export_write_failed"
    const val chars_export_saved = "chars_export_saved"
    const val chars_export_failed = "chars_export_failed"
    const val chars_import_failed = "chars_import_failed"
    const val chars_title = "chars_title"
    const val chars_ai_create = "chars_ai_create"
    const val chars_import_cd = "chars_import_cd"
    const val chars_search_close_cd = "chars_search_close_cd"
    const val chars_search_cd = "chars_search_cd"
    const val chars_new_character = "chars_new_character"
    const val chars_search_placeholder = "chars_search_placeholder"
    const val chars_clear_cd = "chars_clear_cd"
    const val chars_no_match = "chars_no_match"
    const val chars_empty_list = "chars_empty_list"
    const val chars_empty_hint = "chars_empty_hint"
    const val chars_more_options_cd = "chars_more_options_cd"
    const val chars_ai_edit = "chars_ai_edit"
    const val chars_write_worldbook = "chars_write_worldbook"
    const val chars_duplicate = "chars_duplicate"
    const val chars_export_json = "chars_export_json"
    const val chars_delete = "chars_delete"
    const val chars_delete_title = "chars_delete_title"
    const val chars_delete_confirm = "chars_delete_confirm"
    const val chars_cancel = "chars_cancel"
    const val chars_detail_title = "chars_detail_title"
    const val chars_back_cd = "chars_back_cd"
    const val chars_create_character = "chars_create_character"
    const val chars_save_cd = "chars_save_cd"
    const val chars_image_parse_failed = "chars_image_parse_failed"
    const val chars_read_image_failed = "chars_read_image_failed"
    const val chars_back_to_list = "chars_back_to_list"
    const val chars_avatar_preview_cd = "chars_avatar_preview_cd"
    const val chars_card_section = "chars_card_section"
    const val chars_name_only_hint = "chars_name_only_hint"
    const val chars_character_id = "chars_character_id"
    const val chars_pick_avatar_optional = "chars_pick_avatar_optional"
    const val chars_change_avatar = "chars_change_avatar"
    const val chars_field_name = "chars_field_name"
    const val chars_name_required = "chars_name_required"
    const val chars_field_description = "chars_field_description"
    const val chars_field_personality = "chars_field_personality"
    const val chars_field_scenario = "chars_field_scenario"
    const val chars_field_first_message = "chars_field_first_message"
    const val chars_alternate_greetings = "chars_alternate_greetings"
    const val chars_greeting_n = "chars_greeting_n"
    const val chars_remove_greeting_cd = "chars_remove_greeting_cd"
    const val chars_add_greeting = "chars_add_greeting"
    const val chars_field_example_messages = "chars_field_example_messages"
    const val chars_field_creator_notes = "chars_field_creator_notes"
    const val chars_field_system_prompt = "chars_field_system_prompt"
    const val chars_field_post_history = "chars_field_post_history"
    const val chars_field_creator = "chars_field_creator"
    const val chars_field_version = "chars_field_version"
    const val chars_field_tags = "chars_field_tags"
    const val chars_remove_tag_cd = "chars_remove_tag_cd"
    const val chars_add_tag = "chars_add_tag"
    const val chars_add_cd = "chars_add_cd"
    const val chars_character_book = "chars_character_book"
    const val chars_book_entries = "chars_book_entries"
    const val chars_world_binding = "chars_world_binding"
    const val chars_world_unbound = "chars_world_unbound"
    const val chars_world_missing = "chars_world_missing"
    const val chars_pick_worldbook = "chars_pick_worldbook"
    const val chars_save_changes = "chars_save_changes"
    const val chars_world_none = "chars_world_none"
    const val chars_world_empty_hint = "chars_world_empty_hint"
    const val chars_entries_count = "chars_entries_count"
    const val about_unknown = "about_unknown"
    const val about_title = "about_title"
    const val about_version = "about_version"
    const val about_app_desc = "about_app_desc"
    const val about_based_on_st = "about_based_on_st"
    const val about_st_desc = "about_st_desc"
    const val about_visit_st = "about_visit_st"
    const val about_license = "about_license"
    const val about_license_free_software = "about_license_free_software"
    const val about_license_warranty = "about_license_warranty"
    const val about_source_code = "about_source_code"
    const val about_open_source = "about_open_source"
    const val about_credits = "about_credits"
    const val about_built_with = "about_built_with"
    const val about_card_format = "about_card_format"
    const val about_tech_stack = "about_tech_stack"
    const val about_thanks_community = "about_thanks_community"
    const val chat_memory_paused = "chat_memory_paused"
    const val chat_memory_label = "chat_memory_label"
    const val chat_back = "chat_back"
    const val chat_card_interface = "chat_card_interface"
    const val chat_sessions = "chat_sessions"
    const val chat_delete_session = "chat_delete_session"
    const val chat_new_session = "chat_new_session"
    const val chat_more_options = "chat_more_options"
    const val chat_long_term_memory = "chat_long_term_memory"
    const val chat_chat_background = "chat_chat_background"
    const val chat_clear_background = "chat_clear_background"
    const val chat_switch_persona = "chat_switch_persona"
    const val chat_error_save_image = "chat_error_save_image"
    const val chat_error_read_image = "chat_error_read_image"
    const val chat_default_character_name = "chat_default_character_name"
    const val chat_view_generated_images = "chat_view_generated_images"
    const val chat_generated_images_title = "chat_generated_images_title"
    const val chat_hide_prompt = "chat_hide_prompt"
    const val chat_view_image_prompt = "chat_view_image_prompt"
    const val chat_delete = "chat_delete"
    const val chat_close = "chat_close"
    const val chat_cancel = "chat_cancel"
    const val chat_delete_image_title = "chat_delete_image_title"
    const val chat_delete_image_message = "chat_delete_image_message"
    const val chat_delete_session_message = "chat_delete_session_message"
    const val chat_image_gen_failed = "chat_image_gen_failed"
    const val chat_scene_diagnostic_title = "chat_scene_diagnostic_title"
    const val chat_copy_diagnostic = "chat_copy_diagnostic"
    const val chat_exported = "chat_exported"
    const val chat_export_failed = "chat_export_failed"
    const val chat_actions = "chat_actions"
    const val chat_regenerate = "chat_regenerate"
    const val chat_export_generation_diagnostics = "chat_export_generation_diagnostics"
    const val chat_export_raw_response = "chat_export_raw_response"
    const val chat_edit = "chat_edit"
    const val chat_bubble_delete = "chat_bubble_delete"
    const val chat_no_body = "chat_no_body"
    const val chat_retry = "chat_retry"
    const val chat_hide_image_prompt = "chat_hide_image_prompt"
    const val chat_bubble_view_image_prompt = "chat_bubble_view_image_prompt"
    const val chat_reasoning = "chat_reasoning"
    const val chat_reasoning_expand_hint = "chat_reasoning_expand_hint"
    const val chat_bubble_cancel = "chat_bubble_cancel"
    const val chat_bubble_save = "chat_bubble_save"
    const val chat_image_content_desc = "chat_image_content_desc"
    const val chat_generating_image = "chat_generating_image"
    const val chat_cancel_image_gen = "chat_cancel_image_gen"
    const val chat_remove_attachment = "chat_remove_attachment"
    const val chat_add_image = "chat_add_image"
    const val chat_generate_image = "chat_generate_image"
    const val chat_input_hint = "chat_input_hint"
    const val chat_stop_generation = "chat_stop_generation"
    const val chat_send_message = "chat_send_message"
    const val chat_select_memory_mode_title = "chat_select_memory_mode_title"
    const val chat_select_memory_mode_message = "chat_select_memory_mode_message"
    const val chat_memory_manager_title = "chat_memory_manager_title"
    const val chat_memory_ready = "chat_memory_ready"
    const val chat_memory_global_disabled = "chat_memory_global_disabled"
    const val chat_memory_locked_none = "chat_memory_locked_none"
    const val chat_memory_needs_rebuild = "chat_memory_needs_rebuild"
    const val chat_rebuild_vectors = "chat_rebuild_vectors"
    const val chat_show_active_only = "chat_show_active_only"
    const val chat_show_inactive = "chat_show_inactive"
    const val chat_memory_inactive_prefix = "chat_memory_inactive_prefix"
    const val chat_memory_source_label = "chat_memory_source_label"
    const val chat_memory_source_manual = "chat_memory_source_manual"
    const val chat_correct = "chat_correct"
    const val chat_memory_delete = "chat_memory_delete"
    const val chat_memory_close = "chat_memory_close"
    const val chat_retry_pending = "chat_retry_pending"
    const val chat_backfill_history = "chat_backfill_history"
    const val chat_backfill_title = "chat_backfill_title"
    const val chat_backfill_message = "chat_backfill_message"
    const val chat_start_backfill = "chat_start_backfill"
    const val chat_memory_cancel = "chat_memory_cancel"
    const val chat_rebuild_vectors_message = "chat_rebuild_vectors_message"
    const val chat_start = "chat_start"
    const val chat_correct_memory_title = "chat_correct_memory_title"
    const val chat_content_label = "chat_content_label"
    const val chat_memory_save = "chat_memory_save"
    const val chat_image_generation_title = "chat_image_generation_title"
    const val chat_engine_label = "chat_engine_label"
    const val chat_view_last_diagnostic = "chat_view_last_diagnostic"
    const val chat_engine_not_configured = "chat_engine_not_configured"
    const val chat_summarize_scene = "chat_summarize_scene"
    const val chat_positive_prompt = "chat_positive_prompt"
    const val chat_summarize_scene_hint = "chat_summarize_scene_hint"
    const val chat_negative_prompt = "chat_negative_prompt"
    const val chat_generate = "chat_generate"
    const val chat_image_gen_cancel = "chat_image_gen_cancel"
    const val chat_select_character = "chat_select_character"
    const val chat_no_characters = "chat_no_characters"
    const val chat_import_hint = "chat_import_hint"
    const val chat_character_card_interface = "chat_character_card_interface"
    const val chat_close_character_card_interface = "chat_close_character_card_interface"
    const val chat_previous_page = "chat_previous_page"
    const val chat_next_page = "chat_next_page"
    const val nav_tab_chat = "nav_tab_chat"
    const val nav_tab_characters = "nav_tab_characters"
    const val nav_tab_world = "nav_tab_world"
    const val nav_tab_extensions = "nav_tab_extensions"
    const val nav_tab_settings = "nav_tab_settings"
    const val nav_preset_limit_title = "nav_preset_limit_title"
    const val nav_preset_limit_message = "nav_preset_limit_message"
    const val nav_later = "nav_later"
    const val nav_go_to_preset_settings = "nav_go_to_preset_settings"
    const val nav_qq_group_title = "nav_qq_group_title"
    const val nav_qq_qrcode_desc = "nav_qq_qrcode_desc"
    const val nav_qq_group_name = "nav_qq_group_name"
    const val nav_qq_group_number = "nav_qq_group_number"
    const val nav_qq_group_hint = "nav_qq_group_hint"
    const val nav_got_it = "nav_got_it"
    const val nav_group_number_copied = "nav_group_number_copied"
    const val nav_copy_group_number = "nav_copy_group_number"
    const val nav_update_title = "nav_update_title"
    const val nav_update_message = "nav_update_message"
    const val nav_update_apk_size = "nav_update_apk_size"
    const val nav_update_now = "nav_update_now"
    const val nav_update_download_started = "nav_update_download_started"
    const val ui_placeholder_message = "ui_placeholder_message"
    const val settings_language = "settings_language"
    const val settings_language_system = "settings_language_system"

    /** 资源名 → R.string.* id，供 UiStrings 在运行期解析。 */
    val idByName: Map<String, Int> = mapOf(
        "chars_export_write_failed" to R.string.chars_export_write_failed,
        "chars_export_saved" to R.string.chars_export_saved,
        "chars_export_failed" to R.string.chars_export_failed,
        "chars_import_failed" to R.string.chars_import_failed,
        "chars_title" to R.string.chars_title,
        "chars_ai_create" to R.string.chars_ai_create,
        "chars_import_cd" to R.string.chars_import_cd,
        "chars_search_close_cd" to R.string.chars_search_close_cd,
        "chars_search_cd" to R.string.chars_search_cd,
        "chars_new_character" to R.string.chars_new_character,
        "chars_search_placeholder" to R.string.chars_search_placeholder,
        "chars_clear_cd" to R.string.chars_clear_cd,
        "chars_no_match" to R.string.chars_no_match,
        "chars_empty_list" to R.string.chars_empty_list,
        "chars_empty_hint" to R.string.chars_empty_hint,
        "chars_more_options_cd" to R.string.chars_more_options_cd,
        "chars_ai_edit" to R.string.chars_ai_edit,
        "chars_write_worldbook" to R.string.chars_write_worldbook,
        "chars_duplicate" to R.string.chars_duplicate,
        "chars_export_json" to R.string.chars_export_json,
        "chars_delete" to R.string.chars_delete,
        "chars_delete_title" to R.string.chars_delete_title,
        "chars_delete_confirm" to R.string.chars_delete_confirm,
        "chars_cancel" to R.string.chars_cancel,
        "chars_detail_title" to R.string.chars_detail_title,
        "chars_back_cd" to R.string.chars_back_cd,
        "chars_create_character" to R.string.chars_create_character,
        "chars_save_cd" to R.string.chars_save_cd,
        "chars_image_parse_failed" to R.string.chars_image_parse_failed,
        "chars_read_image_failed" to R.string.chars_read_image_failed,
        "chars_back_to_list" to R.string.chars_back_to_list,
        "chars_avatar_preview_cd" to R.string.chars_avatar_preview_cd,
        "chars_card_section" to R.string.chars_card_section,
        "chars_name_only_hint" to R.string.chars_name_only_hint,
        "chars_character_id" to R.string.chars_character_id,
        "chars_pick_avatar_optional" to R.string.chars_pick_avatar_optional,
        "chars_change_avatar" to R.string.chars_change_avatar,
        "chars_field_name" to R.string.chars_field_name,
        "chars_name_required" to R.string.chars_name_required,
        "chars_field_description" to R.string.chars_field_description,
        "chars_field_personality" to R.string.chars_field_personality,
        "chars_field_scenario" to R.string.chars_field_scenario,
        "chars_field_first_message" to R.string.chars_field_first_message,
        "chars_alternate_greetings" to R.string.chars_alternate_greetings,
        "chars_greeting_n" to R.string.chars_greeting_n,
        "chars_remove_greeting_cd" to R.string.chars_remove_greeting_cd,
        "chars_add_greeting" to R.string.chars_add_greeting,
        "chars_field_example_messages" to R.string.chars_field_example_messages,
        "chars_field_creator_notes" to R.string.chars_field_creator_notes,
        "chars_field_system_prompt" to R.string.chars_field_system_prompt,
        "chars_field_post_history" to R.string.chars_field_post_history,
        "chars_field_creator" to R.string.chars_field_creator,
        "chars_field_version" to R.string.chars_field_version,
        "chars_field_tags" to R.string.chars_field_tags,
        "chars_remove_tag_cd" to R.string.chars_remove_tag_cd,
        "chars_add_tag" to R.string.chars_add_tag,
        "chars_add_cd" to R.string.chars_add_cd,
        "chars_character_book" to R.string.chars_character_book,
        "chars_book_entries" to R.string.chars_book_entries,
        "chars_world_binding" to R.string.chars_world_binding,
        "chars_world_unbound" to R.string.chars_world_unbound,
        "chars_world_missing" to R.string.chars_world_missing,
        "chars_pick_worldbook" to R.string.chars_pick_worldbook,
        "chars_save_changes" to R.string.chars_save_changes,
        "chars_world_none" to R.string.chars_world_none,
        "chars_world_empty_hint" to R.string.chars_world_empty_hint,
        "chars_entries_count" to R.string.chars_entries_count,
        "about_unknown" to R.string.about_unknown,
        "about_title" to R.string.about_title,
        "about_version" to R.string.about_version,
        "about_app_desc" to R.string.about_app_desc,
        "about_based_on_st" to R.string.about_based_on_st,
        "about_st_desc" to R.string.about_st_desc,
        "about_visit_st" to R.string.about_visit_st,
        "about_license" to R.string.about_license,
        "about_license_free_software" to R.string.about_license_free_software,
        "about_license_warranty" to R.string.about_license_warranty,
        "about_source_code" to R.string.about_source_code,
        "about_open_source" to R.string.about_open_source,
        "about_credits" to R.string.about_credits,
        "about_built_with" to R.string.about_built_with,
        "about_card_format" to R.string.about_card_format,
        "about_tech_stack" to R.string.about_tech_stack,
        "about_thanks_community" to R.string.about_thanks_community,
        "chat_memory_paused" to R.string.chat_memory_paused,
        "chat_memory_label" to R.string.chat_memory_label,
        "chat_back" to R.string.chat_back,
        "chat_card_interface" to R.string.chat_card_interface,
        "chat_sessions" to R.string.chat_sessions,
        "chat_delete_session" to R.string.chat_delete_session,
        "chat_new_session" to R.string.chat_new_session,
        "chat_more_options" to R.string.chat_more_options,
        "chat_long_term_memory" to R.string.chat_long_term_memory,
        "chat_chat_background" to R.string.chat_chat_background,
        "chat_clear_background" to R.string.chat_clear_background,
        "chat_switch_persona" to R.string.chat_switch_persona,
        "chat_error_save_image" to R.string.chat_error_save_image,
        "chat_error_read_image" to R.string.chat_error_read_image,
        "chat_default_character_name" to R.string.chat_default_character_name,
        "chat_view_generated_images" to R.string.chat_view_generated_images,
        "chat_generated_images_title" to R.string.chat_generated_images_title,
        "chat_hide_prompt" to R.string.chat_hide_prompt,
        "chat_view_image_prompt" to R.string.chat_view_image_prompt,
        "chat_delete" to R.string.chat_delete,
        "chat_close" to R.string.chat_close,
        "chat_cancel" to R.string.chat_cancel,
        "chat_delete_image_title" to R.string.chat_delete_image_title,
        "chat_delete_image_message" to R.string.chat_delete_image_message,
        "chat_delete_session_message" to R.string.chat_delete_session_message,
        "chat_image_gen_failed" to R.string.chat_image_gen_failed,
        "chat_scene_diagnostic_title" to R.string.chat_scene_diagnostic_title,
        "chat_copy_diagnostic" to R.string.chat_copy_diagnostic,
        "chat_exported" to R.string.chat_exported,
        "chat_export_failed" to R.string.chat_export_failed,
        "chat_actions" to R.string.chat_actions,
        "chat_regenerate" to R.string.chat_regenerate,
        "chat_export_generation_diagnostics" to R.string.chat_export_generation_diagnostics,
        "chat_export_raw_response" to R.string.chat_export_raw_response,
        "chat_edit" to R.string.chat_edit,
        "chat_bubble_delete" to R.string.chat_bubble_delete,
        "chat_no_body" to R.string.chat_no_body,
        "chat_retry" to R.string.chat_retry,
        "chat_hide_image_prompt" to R.string.chat_hide_image_prompt,
        "chat_bubble_view_image_prompt" to R.string.chat_bubble_view_image_prompt,
        "chat_reasoning" to R.string.chat_reasoning,
        "chat_reasoning_expand_hint" to R.string.chat_reasoning_expand_hint,
        "chat_bubble_cancel" to R.string.chat_bubble_cancel,
        "chat_bubble_save" to R.string.chat_bubble_save,
        "chat_image_content_desc" to R.string.chat_image_content_desc,
        "chat_generating_image" to R.string.chat_generating_image,
        "chat_cancel_image_gen" to R.string.chat_cancel_image_gen,
        "chat_remove_attachment" to R.string.chat_remove_attachment,
        "chat_add_image" to R.string.chat_add_image,
        "chat_generate_image" to R.string.chat_generate_image,
        "chat_input_hint" to R.string.chat_input_hint,
        "chat_stop_generation" to R.string.chat_stop_generation,
        "chat_send_message" to R.string.chat_send_message,
        "chat_select_memory_mode_title" to R.string.chat_select_memory_mode_title,
        "chat_select_memory_mode_message" to R.string.chat_select_memory_mode_message,
        "chat_memory_manager_title" to R.string.chat_memory_manager_title,
        "chat_memory_ready" to R.string.chat_memory_ready,
        "chat_memory_global_disabled" to R.string.chat_memory_global_disabled,
        "chat_memory_locked_none" to R.string.chat_memory_locked_none,
        "chat_memory_needs_rebuild" to R.string.chat_memory_needs_rebuild,
        "chat_rebuild_vectors" to R.string.chat_rebuild_vectors,
        "chat_show_active_only" to R.string.chat_show_active_only,
        "chat_show_inactive" to R.string.chat_show_inactive,
        "chat_memory_inactive_prefix" to R.string.chat_memory_inactive_prefix,
        "chat_memory_source_label" to R.string.chat_memory_source_label,
        "chat_memory_source_manual" to R.string.chat_memory_source_manual,
        "chat_correct" to R.string.chat_correct,
        "chat_memory_delete" to R.string.chat_memory_delete,
        "chat_memory_close" to R.string.chat_memory_close,
        "chat_retry_pending" to R.string.chat_retry_pending,
        "chat_backfill_history" to R.string.chat_backfill_history,
        "chat_backfill_title" to R.string.chat_backfill_title,
        "chat_backfill_message" to R.string.chat_backfill_message,
        "chat_start_backfill" to R.string.chat_start_backfill,
        "chat_memory_cancel" to R.string.chat_memory_cancel,
        "chat_rebuild_vectors_message" to R.string.chat_rebuild_vectors_message,
        "chat_start" to R.string.chat_start,
        "chat_correct_memory_title" to R.string.chat_correct_memory_title,
        "chat_content_label" to R.string.chat_content_label,
        "chat_memory_save" to R.string.chat_memory_save,
        "chat_image_generation_title" to R.string.chat_image_generation_title,
        "chat_engine_label" to R.string.chat_engine_label,
        "chat_view_last_diagnostic" to R.string.chat_view_last_diagnostic,
        "chat_engine_not_configured" to R.string.chat_engine_not_configured,
        "chat_summarize_scene" to R.string.chat_summarize_scene,
        "chat_positive_prompt" to R.string.chat_positive_prompt,
        "chat_summarize_scene_hint" to R.string.chat_summarize_scene_hint,
        "chat_negative_prompt" to R.string.chat_negative_prompt,
        "chat_generate" to R.string.chat_generate,
        "chat_image_gen_cancel" to R.string.chat_image_gen_cancel,
        "chat_select_character" to R.string.chat_select_character,
        "chat_no_characters" to R.string.chat_no_characters,
        "chat_import_hint" to R.string.chat_import_hint,
        "chat_character_card_interface" to R.string.chat_character_card_interface,
        "chat_close_character_card_interface" to R.string.chat_close_character_card_interface,
        "chat_previous_page" to R.string.chat_previous_page,
        "chat_next_page" to R.string.chat_next_page,
        "nav_tab_chat" to R.string.nav_tab_chat,
        "nav_tab_characters" to R.string.nav_tab_characters,
        "nav_tab_world" to R.string.nav_tab_world,
        "nav_tab_extensions" to R.string.nav_tab_extensions,
        "nav_tab_settings" to R.string.nav_tab_settings,
        "nav_preset_limit_title" to R.string.nav_preset_limit_title,
        "nav_preset_limit_message" to R.string.nav_preset_limit_message,
        "nav_later" to R.string.nav_later,
        "nav_go_to_preset_settings" to R.string.nav_go_to_preset_settings,
        "nav_qq_group_title" to R.string.nav_qq_group_title,
        "nav_qq_qrcode_desc" to R.string.nav_qq_qrcode_desc,
        "nav_qq_group_name" to R.string.nav_qq_group_name,
        "nav_qq_group_number" to R.string.nav_qq_group_number,
        "nav_qq_group_hint" to R.string.nav_qq_group_hint,
        "nav_got_it" to R.string.nav_got_it,
        "nav_group_number_copied" to R.string.nav_group_number_copied,
        "nav_copy_group_number" to R.string.nav_copy_group_number,
        "nav_update_title" to R.string.nav_update_title,
        "nav_update_message" to R.string.nav_update_message,
        "nav_update_apk_size" to R.string.nav_update_apk_size,
        "nav_update_now" to R.string.nav_update_now,
        "nav_update_download_started" to R.string.nav_update_download_started,
        "ui_placeholder_message" to R.string.ui_placeholder_message,
        "settings_language" to R.string.settings_language,
        "settings_language_system" to R.string.settings_language_system,
    )

    /** JVM 单测回退：无 Resources 时按 key 解析中文原文。 */
    val fallbackZh: Map<String, String> = mapOf(
        "chars_export_write_failed" to "无法写入所选位置",
        "chars_export_saved" to "已保存 %1\$s.json",
        "chars_export_failed" to "导出失败：%1\$s",
        "chars_import_failed" to "导入失败：%1\$s",
        "chars_title" to "角色",
        "chars_ai_create" to "AI 创建",
        "chars_import_cd" to "导入角色卡",
        "chars_search_close_cd" to "关闭搜索",
        "chars_search_cd" to "搜索",
        "chars_new_character" to "新建角色",
        "chars_search_placeholder" to "按名称或标签搜索...",
        "chars_clear_cd" to "清除",
        "chars_no_match" to "没有匹配的角色",
        "chars_empty_list" to "暂无角色",
        "chars_empty_hint" to "点击“新建角色”开始创建，或从右上角导入角色卡",
        "chars_more_options_cd" to "更多选项",
        "chars_ai_edit" to "AI 编辑",
        "chars_write_worldbook" to "基于此卡写世界书",
        "chars_duplicate" to "复制",
        "chars_export_json" to "导出 JSON",
        "chars_delete" to "删除",
        "chars_delete_title" to "删除角色",
        "chars_delete_confirm" to "确定要删除“%1\$s”吗？此操作无法撤销。",
        "chars_cancel" to "取消",
        "chars_detail_title" to "角色详情",
        "chars_back_cd" to "返回",
        "chars_create_character" to "创建角色",
        "chars_save_cd" to "保存",
        "chars_image_parse_failed" to "无法解析所选图片",
        "chars_read_image_failed" to "读取图片失败：%1\$s",
        "chars_back_to_list" to "返回角色列表",
        "chars_avatar_preview_cd" to "角色头像预览",
        "chars_card_section" to "角色卡",
        "chars_name_only_hint" to "仅名称必填，其余内容可稍后补充",
        "chars_character_id" to "ID: %1\$s",
        "chars_pick_avatar_optional" to "选择头像（可选）",
        "chars_change_avatar" to "更换头像",
        "chars_field_name" to "名称",
        "chars_name_required" to "请输入角色名称",
        "chars_field_description" to "描述",
        "chars_field_personality" to "性格",
        "chars_field_scenario" to "场景",
        "chars_field_first_message" to "开场白",
        "chars_alternate_greetings" to "替代开场白",
        "chars_greeting_n" to "开场白 %1\$d",
        "chars_remove_greeting_cd" to "移除替代开场白",
        "chars_add_greeting" to "添加替代开场白",
        "chars_field_example_messages" to "示例对话",
        "chars_field_creator_notes" to "创建者备注",
        "chars_field_system_prompt" to "系统提示词（可选）",
        "chars_field_post_history" to "历史后指令（可选）",
        "chars_field_creator" to "创作者",
        "chars_field_version" to "角色版本",
        "chars_field_tags" to "标签",
        "chars_remove_tag_cd" to "移除标签",
        "chars_add_tag" to "添加标签",
        "chars_add_cd" to "添加",
        "chars_character_book" to "角色书",
        "chars_book_entries" to "“%1\$s” · %2\$d 条条目",
        "chars_world_binding" to "世界书绑定",
        "chars_world_unbound" to "未绑定（仅使用上方角色书）",
        "chars_world_missing" to "“%1\$s”（该世界书未导入或已删除）",
        "chars_pick_worldbook" to "选择世界书",
        "chars_save_changes" to "保存修改",
        "chars_world_none" to "不绑定",
        "chars_world_empty_hint" to "暂无世界书。请先在“世界书”页导入或创建。",
        "chars_entries_count" to "%1\$d 条条目",
        "about_unknown" to "未知",
        "about_title" to "关于",
        "about_version" to "版本 %1\$s",
        "about_app_desc" to "面向 AI 角色扮演聊天的原生 Android 客户端。",
        "about_based_on_st" to "基于 SillyTavern",
        "about_st_desc" to "tellev 是基于 SillyTavern 兼容格式构建的原生客户端，沿用角色卡、世界书和主要数据结构，以便和原项目数据互通。",
        "about_visit_st" to "访问 SillyTavern",
        "about_license" to "许可证",
        "about_license_free_software" to "本程序是自由软件：你可以按照自由软件基金会发布的 GNU Affero General Public License 第 3 版或更新版本重新分发或修改它。",
        "about_license_warranty" to "本程序按“原样”分发，不提供任何担保，包括适销性或特定用途适用性的默示担保。详情请参阅 GNU Affero General Public License。",
        "about_source_code" to "源代码",
        "about_open_source" to "tellev 是开源项目，欢迎贡献。",
        "about_credits" to "致谢",
        "about_built_with" to "使用 Jetpack Compose 和 Material 3 构建。",
        "about_card_format" to "角色卡格式基于 SillyTavern V2/V3 规格。",
        "about_tech_stack" to "网络层使用 OkHttp，JSON 处理使用 kotlinx.serialization。",
        "about_thanks_community" to "感谢 SillyTavern 社区。",
        "chat_memory_paused" to "已暂停",
        "chat_memory_label" to "记忆：%1\$s",
        "chat_back" to "返回",
        "chat_card_interface" to "卡片界面",
        "chat_sessions" to "会话",
        "chat_delete_session" to "删除会话",
        "chat_new_session" to "新建会话",
        "chat_more_options" to "更多选项",
        "chat_long_term_memory" to "长期记忆…",
        "chat_chat_background" to "聊天背景…",
        "chat_clear_background" to "清除背景",
        "chat_switch_persona" to "切换人设",
        "chat_error_save_image" to "保存图片失败：%1\$s",
        "chat_error_read_image" to "读取图片失败：%1\$s",
        "chat_default_character_name" to "助手",
        "chat_view_generated_images" to "查看生成图片（%1\$d）",
        "chat_generated_images_title" to "生成图片",
        "chat_hide_prompt" to "收起提示词",
        "chat_view_image_prompt" to "查看图片提示词",
        "chat_delete" to "删除",
        "chat_close" to "关闭",
        "chat_cancel" to "取消",
        "chat_delete_image_title" to "删除图片",
        "chat_delete_image_message" to "将永久删除这张图片文件，无法恢复。",
        "chat_delete_session_message" to "将永久删除「%1\$s」的全部消息、图片与聊天背景，无法恢复。",
        "chat_image_gen_failed" to "生图失败",
        "chat_scene_diagnostic_title" to "场景总结诊断",
        "chat_copy_diagnostic" to "复制诊断",
        "chat_exported" to "已导出",
        "chat_export_failed" to "导出失败",
        "chat_actions" to "操作",
        "chat_regenerate" to "重新生成",
        "chat_export_generation_diagnostics" to "导出生成诊断",
        "chat_export_raw_response" to "导出原始回复",
        "chat_edit" to "编辑",
        "chat_bubble_delete" to "删除",
        "chat_no_body" to "未收到正文",
        "chat_retry" to "重试",
        "chat_hide_image_prompt" to "收起图片提示词",
        "chat_bubble_view_image_prompt" to "查看图片提示词",
        "chat_reasoning" to "思考过程",
        "chat_reasoning_expand_hint" to "思考过程 · 点击展开",
        "chat_bubble_cancel" to "取消",
        "chat_bubble_save" to "保存",
        "chat_image_content_desc" to "聊天图片",
        "chat_generating_image" to "正在生成图片…",
        "chat_cancel_image_gen" to "取消生图",
        "chat_remove_attachment" to "移除附件",
        "chat_add_image" to "添加图片",
        "chat_generate_image" to "生成图片",
        "chat_input_hint" to "输入消息",
        "chat_stop_generation" to "停止生成",
        "chat_send_message" to "发送消息",
        "chat_select_memory_mode_title" to "为这条对话选择记忆模式",
        "chat_select_memory_mode_message" to "选择后仅这条对话使用该模式，之后不能转换。打开它时会自动切回相应模式。旧聊天记录不会自动整理；可稍后手动补建。",
        "chat_memory_manager_title" to "长期记忆 · %1\$s",
        "chat_memory_ready" to "就绪",
        "chat_memory_global_disabled" to "全局记忆开关已关闭，提取和注入均暂停。",
        "chat_memory_locked_none" to "此对话已锁定为无记忆。",
        "chat_memory_needs_rebuild" to "聊天内容已变更，旧提取结果已停用。请手动重建。",
        "chat_rebuild_vectors" to "重建向量索引",
        "chat_show_active_only" to "只看有效记忆",
        "chat_show_inactive" to "显示已失效记忆",
        "chat_memory_inactive_prefix" to "[已失效]",
        "chat_memory_source_label" to "来源：%1\$s",
        "chat_memory_source_manual" to "用户手动维护",
        "chat_correct" to "纠正",
        "chat_memory_delete" to "删除",
        "chat_memory_close" to "关闭",
        "chat_retry_pending" to "重试待处理",
        "chat_backfill_history" to "补建历史",
        "chat_backfill_title" to "补建历史记忆",
        "chat_backfill_message" to "将整理本对话约 %1\$d 条角色回复，预计至少 %2\$d 次记忆模型请求。重新提取会替换当前记忆并产生模型费用。",
        "chat_start_backfill" to "开始补建",
        "chat_memory_cancel" to "取消",
        "chat_rebuild_vectors_message" to "将为约 %1\$d 条记忆调用向量接口；这可能产生费用。",
        "chat_start" to "开始",
        "chat_correct_memory_title" to "纠正记忆",
        "chat_content_label" to "内容",
        "chat_memory_save" to "保存",
        "chat_image_generation_title" to "生成图片",
        "chat_engine_label" to "生图引擎",
        "chat_view_last_diagnostic" to "查看上次总结诊断",
        "chat_engine_not_configured" to "（未配置）",
        "chat_summarize_scene" to "由 AI 总结当前场景",
        "chat_positive_prompt" to "正面提示词",
        "chat_summarize_scene_hint" to "将使用当前对话最近的上下文自动生成生图提示词。",
        "chat_negative_prompt" to "负面提示词（可选）",
        "chat_generate" to "生成",
        "chat_image_gen_cancel" to "取消",
        "chat_select_character" to "选择角色",
        "chat_no_characters" to "暂无角色",
        "chat_import_hint" to "请先在“角色”页导入角色卡。",
        "chat_character_card_interface" to "角色卡界面",
        "chat_close_character_card_interface" to "关闭角色卡界面",
        "chat_previous_page" to "上一页",
        "chat_next_page" to "下一页",
        "nav_tab_chat" to "聊天",
        "nav_tab_characters" to "角色",
        "nav_tab_world" to "世界书",
        "nav_tab_extensions" to "扩展",
        "nav_tab_settings" to "设置",
        "nav_preset_limit_title" to "请检查当前生成预设",
        "nav_preset_limit_message" to "旧版默认预设的上下文上限仅 4096、输出上限仅 300，可能造成世界书和回复被严重截断。新版内置默认值已调整为 1,000,000 / 131,072；导入或自行修改过的预设不会被强制覆盖，请前往“设置 → 生成预设”切换或检查当前预设。",
        "nav_later" to "稍后",
        "nav_go_to_preset_settings" to "去设置预设",
        "nav_qq_group_title" to "加入 QQ 交流群",
        "nav_qq_qrcode_desc" to "QQ 群二维码",
        "nav_qq_group_name" to "tellev酒馆交流群",
        "nav_qq_group_number" to "群号：754350480",
        "nav_qq_group_hint" to "扫码或搜索群号加入，反馈问题、交流玩法。",
        "nav_got_it" to "我知道了",
        "nav_group_number_copied" to "已复制群号",
        "nav_copy_group_number" to "复制群号",
        "nav_update_title" to "发现新版本",
        "nav_update_message" to "新版本 %1\$s 已发布，当前版本 v%2\$s。",
        "nav_update_apk_size" to "安装包约 %1\$s MB",
        "nav_update_now" to "立即更新",
        "nav_update_download_started" to "开始下载新版本…",
        "ui_placeholder_message" to "架构入口已就绪，具体功能实现放在当前模块。",
        "settings_language" to "语言",
        "settings_language_system" to "跟随系统",
    )
}
